In [2]:
#Dicision tree algorithem
#choose a best attribute our the dataset
# significant of dataset split our dataset
# used independent variable to predict dependent variable
#depth-level for selection of attribute
#best machine learing algorithm for classification problem


In [3]:
#import packages
import pandas as pd
import numpy as np
import scipy.optimize as opt
import pylab as pl
import matplotlib.pyplot as plt
%matplotlib inline


In [4]:
#read a data set
df=pd.read_csv("drug200.csv")

df.head(6)

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY
5   22   F  NORMAL        HIGH    8.607  drugX

In [5]:
df.columns

Index(['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K', 'Drug'], dtype='object')

In [6]:
df.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [7]:
df.shape

(200, 6)

In [8]:
df.info() #information show such as number of rows and number of columns and datatypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [9]:
x=df[['Age','Sex','BP','Cholesterol','Na_to_K']].values
x[0:10]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043],
       [22, 'F', 'NORMAL', 'HIGH', 8.607000000000001],
       [49, 'F', 'NORMAL', 'HIGH', 16.275],
       [41, 'M', 'LOW', 'HIGH', 11.037],
       [60, 'M', 'NORMAL', 'HIGH', 15.171],
       [43, 'M', 'LOW', 'NORMAL', 19.368]], dtype=object)

In [10]:
x[0:2,1]#find a particular value

array(['F', 'M'], dtype=object)

In [11]:
x[0:1,0]

array([23], dtype=object)

In [12]:
#import DecisionTreeClassifier from sklearn.tree
from sklearn.tree import DecisionTreeClassifier

In [13]:
#preprocessing
from sklearn import preprocessing
 #conversatin from object(string) to-->numeric/int  similar work from others
le_sex=preprocessing.LabelEncoder()
le_sex.fit(['F','M'])#'F'-0,'M'-1
x[:,1]=le_sex.transform(x[:,1])
x[0:5]

array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.113999999999999],
       [28, 0, 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 0, 'LOW', 'HIGH', 18.043]], dtype=object)

In [14]:
le_BP=preprocessing.LabelEncoder()
le_BP.fit(['HIGH','LOW','NORMAL'])
x[:,2]=le_BP.transform(x[:,2])
x[0:5]

array([[23, 0, 0, 'HIGH', 25.355],
       [47, 1, 1, 'HIGH', 13.093],
       [47, 1, 1, 'HIGH', 10.113999999999999],
       [28, 0, 2, 'HIGH', 7.797999999999999],
       [61, 0, 1, 'HIGH', 18.043]], dtype=object)

In [15]:
le_Cholesterol=preprocessing.LabelEncoder()
le_Cholesterol.fit(['HIGH','NORMAL'])
x[:,3]=le_Cholesterol.transform(x[:,3])
x[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [16]:
#dependemt variable 
y=df['Drug']
y[0:5]

0    drugY
1    drugC
2    drugC
3    drugX
4    drugY
Name: Drug, dtype: object

In [17]:
 #split the train and test dataset hear train data_set as 70%, and test data_set as 30%
from sklearn.model_selection import train_test_split
x_trainset,x_testset,y_trainset,y_testset=train_test_split(x,y,test_size=0.3,random_state=3)

In [18]:
#train and test size/shape  
print("train",x_trainset.shape ,y_trainset.shape)
print("test",x_testset.shape,y_testset.shape)

train (140, 5) (140,)
test (60, 5) (60,)


In [19]:
#entropy -randomness or inorder on datset
drugtree=DecisionTreeClassifier(criterion='entropy',max_depth=4)
drugtree

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [20]:
#fit the train data_set
drugtree.fit(x_trainset,y_trainset)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [21]:
#predict/ prediction
pred=drugtree.predict(x_testset)

In [22]:
#predict value
print(pred[0:5])

#actual_value
print(y_testset[0:5])

['drugY' 'drugX' 'drugX' 'drugX' 'drugX']
40     drugY
51     drugX
139    drugX
197    drugX
170    drugX
Name: Drug, dtype: object


In [23]:
#find the accuracy
from sklearn import metrics
print("accuracy:",metrics.accuracy_score(pred,y_testset))

accuracy: 0.9833333333333333


In [24]:
#find f1_score/accuracy
from sklearn.metrics import f1_score
f1_score(pred,y_testset,average='weighted')

0.9833514001806685

In [25]:
#machine learning model compatable with array
#decision tree classifier used when data classify more then 2 'object data type' class/attribute
#choose a best attribute
#without y(dependent variable) 
#conversion to int or not create a asarray()method (data is same only predict)